spring.application.name=springboot




spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
logging.level.org.springframework.web=DEBUG
# This tells Spring Boot to look for environment variables
spring.datasource.url=jdbc:postgresql://${DB_HOST}/${DB_NAME}?sslmode=require
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Hibernate settings for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
